Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -14,19 +14,33 @@ if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
 fi
 APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
 
-DEPENDENCY="packages/get-coffee-util"
+if [ ! -f "${ENV_DIR}/DEPENDENCIES" ]; then
+    echo "No dependencies configured. If you wish to include local packages in monorepo with '../<package>' style depencies, set DEPENDENCIES." | indent
+else
+    DEPENDENCIES="$(cat "${ENV_DIR}/DEPENDENCIES")"
+fi
+
+APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
 
 (
     mv "${BUILD_DIR}/${APP_BASE}" "${STAGE}" &&
-    mv "${BUILD_DIR}/${DEPENDENCY}" "${BUILD_DIR}/../"
+    if [ ! -z "$DEPENDENCIES" ]; then
+        echo "Processing dependencies" | indent
+        for DEPENDENCY in ${DEPENDENCIES}; do
+            if [ ! -d "${BUILD_DIR}/${DEPENDENCY}" ]; then
+                echo "Dependency ${DEPENDENCY} not found. Aborting" | indent
+                exit 1
+            fi
+            mv "${BUILD_DIR}/${DEPENDENCY}" "${BUILD_DIR}/../"
+        done
+    fi &&
     rm -rf "${BUILD_DIR}" &&
     mv "${STAGE}/$(basename "$APP_BASE")" "${BUILD_DIR}"
 )
 
 if [ $? -ne 0 ]; then
-    echo "FAILED to copy directory into place" | indent
+    echo "FAILED to copy directories into place" | indent
     exit 1
 fi
 
 echo "Copied ${APP_BASE} to root of app successfully" | indent
-
