Fix silly bug, and output

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,9 +15,11 @@ if [[ -z "${PROCFILE}" ]]; then
     exit 1
 fi
 
-echo "BUILD_DIR IS: ${BUILD_DIR}" | indent
-echo "PROCFILE IS: ${PROCFILE}" | indent
+cp ${BUILD_DIR}/_procfiles/${PROCFILE} ${BUILD_DIR}/Procfile
 
-cp ${BUILD_DIR}/_procfiles/${PROCFILE} ${BUILD_DIR}
+if ! [ $? ]; then
+    echo "FAILED to copy a Procfile" | indent
+    exit 1
+fi
 
 echo "Copied ${PROCFILE} as Procfile successfully" | indent
